# COMMENT: These are two redirect rules with all the fields expanded
# COMMENT: This is an expanded syntax for rules that won't fit in one line
[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = false

  [[redirects]]
  from = "/about"
  to = "/site/about.html"
  status = 301
  force = true